name: Azure Node.js CI/CD

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm ci
      working-directory: ./reactapp  # adjust if your frontend code is in a different directory

    - name: Build
      run: npm run build
      working-directory: ./reactapp

    - name: 'Login to Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.AZURE_FRONTEND_APP_NAME }}
        package: ./frontend/build  # adjust this path to your build output directory

    - name: 'Configure Web App Settings'
      run: |
        az webapp config set --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
                             --name ${{ secrets.AZURE_FRONTEND_APP_NAME }} \
                             --node-version 18-lts

    - name: Verify Deployment
      run: |
        az webapp show --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
                       --name ${{ secrets.AZURE_FRONTEND_APP_NAME }}
